[package]
name = "barcode-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = { version = "*" }
phf = { version = "0.11.1", features = ["macros"] }
